version: "3"

services:
  frontend:
    build: ./src/frontend
    ports:
      - 3002:3002
    depends_on:
      - postservice
    networks:
      - local
  postservice:
    build: ./src/postservice
    ports:
      - 8082:8082
    depends_on:
      - dataprocessingservice
      - mysqlserver
    networks:
      - local
  dataprocessingservice:
    build: ./src/dataprocessingservice
    ports:
      - 5000:5000
    networks:
      - local
  mysqlserver:
    build: ./src/mysqlserver
    ports:
      - 3306:3306
    networks:
      - local
networks:
  local:
    driver: bridge
