version: "3.2"

services:
  nginxloadbalancer:
    build: ./src/nginxloadbalancer
    image: rickygeng97/microservicesapp_nginxloadbalancer
    volumes: 
      - ./src/nginxloadbalancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always
    networks:
      - network1
  frontend:
    build: ./src/frontend
    image: rickygeng97/microservicesapp_frontend
    volumes: 
      - ./src/frontend:/usr/share/nginx/html/frontend
      - ./src/frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3002:3002
    restart: always
    depends_on:
      - zuulserver
      - eurekaserver
      - userservice
      - postservice
      - chatservice
    networks:
      - network1
  zuulserver:
    build: ./src/zuulserver
    image: rickygeng97/microservicesapp_zuulserver
    volumes:
      - type: volume
        source: ./src/zuulserver
        target: /usr/src/zuulserver
    ports:
      - 8762:8762
    restart: always
    depends_on:
      - eurekaserver
    networks:
      - network1
  eurekaserver:
    build: ./src/eurekaserver
    image: rickygeng97/microservicesapp_eurekaserver
    volumes:
      - type: volume
        source: ./src/eurekaserver
        target: /usr/src/eurekaserver
    ports:
      - 8761:8761
    restart: always
    networks:
      - network1
  authservice:
    build: ./src/authservice
    image: rickygeng97/microservicesapp_authservice
    volumes:
      - type: volume
        source: ./src/authservice
        target: /usr/src/authservice
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - eurekaserver
    networks:
      - network1
  userservice:
    build: ./src/userservice
    image: rickygeng97/microservicesapp_userservice
    volumes:
      - type: volume
        source: ./src/userservice
        target: /usr/src/userservice
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - eurekaserver
    networks:
      - network1
  postservice:
    build: ./src/postservice
    image: rickygeng97/microservicesapp_postservice
    volumes:
      - type: volume
        source: ./src/postservice
        target: /usr/src/postservice
      - type: bind
        source: ../datamart_storage
        target: /storage
    ports:
      - 8082:8082
    restart: always
    depends_on:
      - eurekaserver
    networks:
      - network1
  chatservice:
    build: ./src/chatservice
    image: rickygeng97/microservicesapp_chatservice
    volumes:
      - type: volume
        source: ./src/chatservice
        target: /usr/src/chatservice
    ports:
      - 8083:8083
    restart: always
    depends_on:
      - eurekaserver
    networks:
      - network1
  dataprocessingservice:
    build: ./src/dataprocessingservice
    image: rickygeng97/microservicesapp_dataprocessingservice
    volumes:
      - ./src/dataprocessingservice:/usr/src/dataprocessingservice
    ports:
      - 5000:5000
    networks:
      - network1
networks:
  network1:
    driver: bridge
