server:
  port: 8080
spring:
  application:
    name: authservice
  datasource:
    username: mysqladmin@microserivcesapp-mysqlserver
    password: Microservicesapp!
    url: jdbc:mysql://microserivcesapp-mysqlserver.mysql.database.azure.com:3306/microservices_app?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
mybatis:
  mapper-locations: classpath:com/microservices_app/authservice/**/xml/*Mapper.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.1:8761/eureka/
    instance:
      preferIpAddress: true