server:
  port: 8083

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://172.17.0.1:3306/datamart?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
mybatis:
  mapper-locations: classpath:com/microservices_app/chatservice/**/xml/*Mapper.xml
