server:
  port: 8762
spring:
  application:
    name: zuulserver
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  ignored-services: "*"
  routes:
    auth:
      stripPrefix: false
      path: /auth/**
      serviceId: authservice
    posts:
      stripPrefix: false
      path: /posts/**
      serviceId: postservice
    datasets:
      stripPrefix: false
      path: /datasets/**
      serviceId: postservice
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled:hystrix: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000