server:
  port: 8082

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysqlserver:3306/microservices_app?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
mybatis:
  mapper-locations: classpath:com/microservices_app/postservice/**/xml/*Mapper.xml
